name: Publish to NPM

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
    
      - name: Publish package on NPM 📦
        run: |
          version=$(eval npm show cooklens-types version)
          nextVersion=$(echo $version | awk -F. -v OFS=. '{$NF += 1 ; print}')
          npm publish $nextVersion
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}
